### ISSUE TITLE
There is a dependency to vaadin-client-compiler

### ISSUE THREAD

**Issue by mstahv** [Wnt/Vaadin-Field-arithmetics#1]
Never add vaadin-client-compiler as direct dependency like this:
https://github.com/Wnt/Vaadin-Field-arithmetics/blob/master/fieldarithmetics/pom.xml#L95

If that is really needed in the add-on, which I highly doubt, that should be declared as provided.

**Comment by Wnt** [comment]
Dependency removed in c9d708553c5bccbe50b7029424306905a3d900f3
